#!/bin/bash

_jssl_completions() {
  local cur prev opts ops
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  opts="--port -p --alias -a --help -h --version -v --list -l"
  ops="ping install uninstall"

  # Ha csak a host után jön a művelet
  if [[ ${COMP_CWORD} -eq 2 ]]; then
    COMPREPLY=( $(compgen -W "${ops}" -- "$cur") )
    return 0
  fi

  case "$prev" in
    -p|--port)
      COMPREPLY=( $(compgen -W "443 8443 9443" -- "$cur") )
      return 0
      ;;
    -a|--alias)
      COMPREPLY=( $(compgen -W "jssl_example jssl_localhost" -- "$cur") )
      return 0
      ;;
    *)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "${opts}" -- "$cur") )
        return 0
      fi
      ;;
  esac
}